#!/bin/bash

echo ""
echo "Introduze los datos para abrir SQLcmd"
echo -n "Usuario: "
read user
echo -n "Contraseña: "
read pssw
echo -n "Servidor: "
read host

echo ""
echo "Abriendo SQLcmd..."

if [[ -z "$1" && -z "$2" ]]
then
    sqlcmd -S $host -U $user -P "$pssw"
elif [ -z "$2" ]
then
    sqlcmd -S $host -U $user -P "$pssw" -i $1
else
    sqlcmd -S $host -U $user -P "$pssw" -i $1 -o $2
fi

echo ""
